name: drink_calculator
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  args: ^2.0.0
  intl: ^0.17.0

dev_dependencies:
  lint: ^1.10.0
  test: ^1.16.0
